import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiBell, FiRefreshCw, FiX } from "react-icons/fi";
import { useToast } from "../components/ToastProvider";
import {
  dismissNotification,
  fetchPendingNotifications,
  generateNotifications,
} from "../lib/notifications";
import { useNotifications } from "../context/NotificationsContext";
import Badge from "../components/ui/Badge";
import Button from "../components/ui/Button";
import Card from "../components/ui/Card";
import EmptyState from "../components/ui/EmptyState";
import PageHeader from "../components/ui/PageHeader";
import Skeleton from "../components/ui/Skeleton";


export default function NotificationsPage() {
  const toast = useToast();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState(null);
  const [generating, setGenerating] = useState(false);
  const { refreshNotificationCount } = useNotifications();


  const load = async () => {
    setLoading(true);
    try {
      const data = await fetchPendingNotifications();
      setItems(Array.isArray(data) ? data : []);
      await refreshNotificationCount();
    } catch (e) {
      toast.error("Failed to load notifications", e?.message || "Unknown error");
      setItems([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const result = await generateNotifications();
      await load();
      toast.success(
        "Notifications refreshed",
        `Created ${result.created}, skipped ${result.skipped}`
      );
    } catch (e) {
      toast.error("Failed to generate notifications", e?.message || "Unknown error");
    } finally {
      setGenerating(false);
    }
  };

  const handleDismiss = async (id) => {
    setBusyId(id);
    try {
      await dismissNotification(id);
      setItems((prev) => prev.filter((n) => n.id !== id));
        await refreshNotificationCount();
      toast.success("Dismissed", "Notification removed");
    } catch (e) {
      toast.error("Failed to dismiss notification", e?.message || "Unknown error");
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div className="space-y-8">
      <PageHeader
        eyebrow="Notifications"
        title="Pending reminders"
        description="Your pending reminders and nudges generated by the backend."
        actions={
          <>
            <Button
              variant="secondary"
            onClick={load}
          >
            <FiRefreshCw />
            Refresh
            </Button>

            <Button
            onClick={handleGenerate}
            disabled={generating}
          >
            {generating ? "Generating..." : "Generate Notifications"}
            </Button>
          </>
        }
      />

      {loading ? (
        <div className="grid gap-4 md:grid-cols-2">
          {Array.from({ length: 4 }).map((_, i) => (
            <Skeleton key={i} className="h-[140px]" />
          ))}
        </div>
      ) : items.length === 0 ? (
        <EmptyState
          title="No pending notifications"
          description="Generate a fresh batch or keep building momentum and they will appear here when needed."
          actionLabel={generating ? "Generating..." : "Generate Notifications"}
          onAction={handleGenerate}
        />
      ) : (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {items.map((item) => (
            <Card
              key={item.id}
              className="transition hover:-translate-y-0.5 hover:shadow-[0_10px_28px_rgba(15,23,42,0.08)]"
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <div className="flex items-center gap-2">
                    <FiBell className="text-[#3337a6]" />
                    <div className="text-lg font-semibold text-slate-950">{item.title}</div>
                  </div>
                  <div className="mt-2 text-sm leading-6 text-slate-600">{item.message}</div>
                </div>

                <button
                  onClick={() => handleDismiss(item.id)}
                  disabled={busyId === item.id}
                  className="rounded-lg p-2 text-slate-500 ring-1 ring-slate-200 hover:bg-slate-50 hover:text-red-700 disabled:opacity-60"
                  title="Dismiss"
                  type="button"
                >
                  <FiX />
                </button>
              </div>

              <div className="mt-5 flex items-center justify-between gap-3">
                <div className="text-xs text-slate-500">
                  Scheduled: {item.scheduled_for}
                </div>
                <Badge tone="indigo">{item.nudge_type}</Badge>

                {item.action_path ? (
                  <Button
                    as={Link}
                    to={item.action_path}
                    variant="secondary"
                    size="sm"
                  >
                    Open
                  </Button>
                ) : null}
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
