import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { FiBell, FiRefreshCw, FiX } from "react-icons/fi";
import { useToast } from "../components/ToastProvider";
import {
  dismissNotification,
  fetchPendingNotifications,
  generateNotifications,
} from "../lib/notifications";
import { useNotifications } from "../context/NotificationsContext";


export default function NotificationsPage() {
  const toast = useToast();
  const [items, setItems] = useState([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState(null);
  const [generating, setGenerating] = useState(false);
  const { refreshNotificationCount } = useNotifications();


  const load = async () => {
    setLoading(true);
    try {
      const data = await fetchPendingNotifications();
      setItems(Array.isArray(data) ? data : []);
      await refreshNotificationCount();
    } catch (e) {
      toast.error("Failed to load notifications", e?.message || "Unknown error");
      setItems([]);
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    load();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const handleGenerate = async () => {
    setGenerating(true);
    try {
      const result = await generateNotifications();
      await load();
      toast.success(
        "Notifications refreshed",
        `Created ${result.created}, skipped ${result.skipped}`
      );
    } catch (e) {
      toast.error("Failed to generate notifications", e?.message || "Unknown error");
    } finally {
      setGenerating(false);
    }
  };

  const handleDismiss = async (id) => {
    setBusyId(id);
    try {
      await dismissNotification(id);
      setItems((prev) => prev.filter((n) => n.id !== id));
        await refreshNotificationCount();
      toast.success("Dismissed", "Notification removed");
    } catch (e) {
      toast.error("Failed to dismiss notification", e?.message || "Unknown error");
    } finally {
      setBusyId(null);
    }
  };

  return (
    <div className="space-y-8">
      <div className="flex flex-col gap-4 md:flex-row md:items-end md:justify-between">
        <div>
          <h1 className="text-3xl font-semibold">Notifications</h1>
          <p className="mt-2 text-white/60">
            Your pending reminders and nudges generated by the backend.
          </p>
        </div>

        <div className="flex gap-3">
          <button
            onClick={load}
            className="inline-flex items-center gap-2 rounded-xl bg-white/10 px-4 py-2 text-sm ring-1 ring-white/15 hover:bg-white/15"
          >
            <FiRefreshCw />
            Refresh
          </button>

          <button
            onClick={handleGenerate}
            disabled={generating}
            className="rounded-xl bg-gradient-to-r from-cyan-400 via-fuchsia-400 to-indigo-400 px-4 py-2 text-sm font-semibold text-black disabled:opacity-60"
          >
            {generating ? "Generating..." : "Generate Notifications"}
          </button>
        </div>
      </div>

      {loading ? (
        <div className="grid gap-4 md:grid-cols-2">
          {Array.from({ length: 4 }).map((_, i) => (
            <div
              key={i}
              className="h-[140px] rounded-2xl bg-white/5 ring-1 ring-white/10"
            />
          ))}
        </div>
      ) : items.length === 0 ? (
        <div className="rounded-3xl bg-white/5 p-10 text-center ring-1 ring-white/10">
          <div className="mx-auto grid h-14 w-14 place-items-center rounded-2xl bg-white/10 ring-1 ring-white/15">
            <FiBell className="text-xl" />
          </div>
          <div className="mt-4 text-2xl font-semibold">No pending notifications</div>
          <div className="mt-2 text-white/60">
            Generate a fresh batch or keep building momentum and they’ll appear here when needed.
          </div>

          <button
            onClick={handleGenerate}
            disabled={generating}
            className="mt-6 rounded-xl bg-gradient-to-r from-cyan-400 via-fuchsia-400 to-indigo-400 px-5 py-2 text-sm font-semibold text-black disabled:opacity-60"
          >
            {generating ? "Generating..." : "Generate Notifications"}
          </button>
        </div>
      ) : (
        <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">
          {items.map((item) => (
            <div
              key={item.id}
              className="rounded-2xl bg-white/5 p-6 ring-1 ring-white/10"
            >
              <div className="flex items-start justify-between gap-3">
                <div>
                  <div className="text-lg font-semibold">{item.title}</div>
                  <div className="mt-2 text-sm text-white/60">{item.message}</div>
                </div>

                <button
                  onClick={() => handleDismiss(item.id)}
                  disabled={busyId === item.id}
                  className="rounded-xl bg-white/10 p-2 ring-1 ring-white/15 hover:bg-white/15 disabled:opacity-60"
                  title="Dismiss"
                  type="button"
                >
                  <FiX />
                </button>
              </div>

              <div className="mt-5 flex items-center justify-between gap-3">
                <div className="text-xs text-white/45">
                  Scheduled: {item.scheduled_for}
                </div>

                {item.action_path ? (
                  <Link
                    to={item.action_path}
                    className="rounded-xl bg-white/10 px-3 py-2 text-sm ring-1 ring-white/15 hover:bg-white/15"
                  >
                    Open
                  </Link>
                ) : null}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
